### ISSUE TITLE
First applications: Setup with OpenGeoSys (Windows): Aktualisierung

### ISSUE THREAD

**Issue by ChrisWudel** [pymanga/website#27]
- Es soll eine andere Version als die in den beschreibenden Abbildungen gezeigte heruntergeladen werden.
![grafik](https://github.com/pymanga/website/assets/66413299/d968bf77-ebb8-400b-beae-adec750c1cdb)
- Welche Datei genau heruntergeladen soll hat sich auch antscheindet geändert.
- Abbildung 4 stimmt auch nicht mehr da es keine TreeModelLib mehr gibt. 
![grafik](https://github.com/pymanga/website/assets/66413299/d0a419f7-70a2-4eaf-b3a3-2a35a48d7997)
- Dementsprechend ist der Pfad in Abbildung 6 nicht korrekt.

**Comment by pymanga** [comment]
closed with PR #36
